@startuml
class StorageManager {
  return produto
  return produto
  return null
  return true
  return false
  Date(): new
  Date(): new
  Date(): new
  Date(): new
  Error(inválida'): new
  StorageManager(): new
  upadateDashboard(): Dashboard
  Date(mov.data): new
  abrirModalProduto(null): Produtos
  Date(mov.data): new
  Date(mov.data): new
  Date(): new
  FileReader(): new
  Error(inválido'): new
  Error(backup'): new
  App(): new
  App(): new
}
@enduml